### PR TITLE
Extended CacheTagHelper to utilize MVCCaching

### PR DESCRIPTION
**Pull request by jkerb135**
Updated Xperience package to refresh one to extend the default Cache Tag Helper to utilize MVCCaching implementation.

### CODE REVIEW

**Comment by KenticoDevTrev** [comment]
Looking over the code, am i correct in that the new functionality (except for adding a new CacheTImeInMinutes to the IRepositoryContext), won't impact any existing functionality, as you must use `<cache-scoped />` instead of `<cache />` right?

Additionally, any reason why the version was set to hotfix 16? I don't see anything in there that wasn't available in 5 (.net 5 support)

**Comment by jkerb135** [comment]
Utilizing `<cache />` will utilize the default CacheTagHelper like you have in your examples, you are correct that `<cache-scoped />` will only run when used.

The hotfix was updated to Refresh 1 (13.0.16) because of the use of the `CMS.Helpers.Caching.ICacheDependencyAdapter` in the tag helper to create the change keys for the memory cache also the examples using `<cache-dependency />` which did not exist in Xperience prior refresh 1.

**Comment by KenticoDevTrev** [comment]
Very good points on the cache-dependency availability.

I'm going to have one more person review it tonight and then i'll pull it in, update the package numbers and get it deployed.  Thanks!

**Comment by jkerb135** [comment]
Yeah no problem, also if it makes more sense to change the implementation to utilize an attribute on the CacheTagHelper instead kind of like how you implemented the WidgetSetsTagHelper extension on the Xpereience EditableAreaTagHelper that might be more user friendly than to have to update all existing cache attributes in code if someone wants to utilize it.

`<cache use-scoped additional-keys="" />` would trigger the extended tag helper
`<cache />` would trigger just the cache tag helper

**Comment by jkerb135** [comment]
No problem,

I wonder if it would make more sense to extend the CacheTagHelper with an attribute to reduce the amount of code needing to be changed for people already utilizing the base attribute.

`<cache scoped additional-keys=""  />` Would trigger the extended tag helper
`<cache />` Would trigger only the base tag helper

**Comment by KenticoDevTrev** [comment]
Adding as an additional tag would be easier I think, but your call of you want to refactor, I would say it would be worth it!

**Comment by jkerb135** [comment]
Ok, It has been refactored to run if the `scoped` attribute is added

Will add cache keys created using the ICacheDependencyBuilderFactory

```html
<cache scoped>
   <vc:alerts />
</cache>
```

or

Will add cache keys created using the ICacheDependencyBuilderFactory and the Additional Keys

```html
<cache scoped additional-keys="@(new[] { FluentCacheKey.ForPage().WithDocumentId(footerId.Value) })">
   <vc:render-page document-id="@footerId.Value"/>
</cache>
```

Added a check for `vary-by-user="true"` to add the current authenticated user cache key into the store also added a `vary-by-contact` attribute to add the current contacts guid into the store as well as set `VaryByCookie = "CurrentContact"` to look at the CurrentContact cookie value Kentico sets.

**Comment by KenticoDevTrev** [comment]
Nice add! Trying to get this and another pull request done soon, a little swamped but hoping for at least mid week

**Pull request merged**
